// <auto-generated />
using System;
using Evently.Modules.Users.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Evently.Modules.Users.Infrastructure.Database.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20260404172909_Create_Database")]
    partial class Create_Database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("users")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Evently.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("inbox_messages", "users");
                });

            modelBuilder.Entity("Evently.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("InboxMessageId", "Name");

                    b.ToTable("inbox_message_consumers", "users");
                });

            modelBuilder.Entity("Evently.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("outbox_messages", "users");
                });

            modelBuilder.Entity("Evently.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("OutboxMessageId", "Name");

                    b.ToTable("outbox_message_consumers", "users");
                });

            modelBuilder.Entity("Evently.Modules.Users.Domain.Users.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Code");

                    b.ToTable("permissions", "users");

                    b.HasData(
                        new
                        {
                            Code = "users:read"
                        },
                        new
                        {
                            Code = "users:update"
                        },
                        new
                        {
                            Code = "events:read"
                        },
                        new
                        {
                            Code = "events:search"
                        },
                        new
                        {
                            Code = "events:update"
                        },
                        new
                        {
                            Code = "ticket-types:read"
                        },
                        new
                        {
                            Code = "ticket-types:update"
                        },
                        new
                        {
                            Code = "categories:read"
                        },
                        new
                        {
                            Code = "categories:update"
                        },
                        new
                        {
                            Code = "carts:read"
                        },
                        new
                        {
                            Code = "carts:add"
                        },
                        new
                        {
                            Code = "carts:remove"
                        },
                        new
                        {
                            Code = "orders:read"
                        },
                        new
                        {
                            Code = "orders:create"
                        },
                        new
                        {
                            Code = "tickets:read"
                        },
                        new
                        {
                            Code = "tickets:check-in"
                        },
                        new
                        {
                            Code = "event-statistics:read"
                        });
                });

            modelBuilder.Entity("Evently.Modules.Users.Domain.Users.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("roles", "users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("43f0ccca-e92a-4fa9-8d76-95e0746d33f6"),
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        },
                        new
                        {
                            Id = new Guid("7e7e4db6-0880-4b6a-b5d3-2d50e183f960"),
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Evently.Modules.Users.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("Users", "users");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<string>("PermissionCode")
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionCode", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("role_permissions", "users");

                    b.HasData(
                        new
                        {
                            PermissionCode = "users:read",
                            RoleId = new Guid("43f0ccca-e92a-4fa9-8d76-95e0746d33f6")
                        },
                        new
                        {
                            PermissionCode = "users:update",
                            RoleId = new Guid("43f0ccca-e92a-4fa9-8d76-95e0746d33f6")
                        },
                        new
                        {
                            PermissionCode = "events:search",
                            RoleId = new Guid("43f0ccca-e92a-4fa9-8d76-95e0746d33f6")
                        },
                        new
                        {
                            PermissionCode = "ticket-types:read",
                            RoleId = new Guid("43f0ccca-e92a-4fa9-8d76-95e0746d33f6")
                        },
                        new
                        {
                            PermissionCode = "carts:read",
                            RoleId = new Guid("43f0ccca-e92a-4fa9-8d76-95e0746d33f6")
                        },
                        new
                        {
                            PermissionCode = "carts:add",
                            RoleId = new Guid("43f0ccca-e92a-4fa9-8d76-95e0746d33f6")
                        },
                        new
                        {
                            PermissionCode = "carts:remove",
                            RoleId = new Guid("43f0ccca-e92a-4fa9-8d76-95e0746d33f6")
                        },
                        new
                        {
                            PermissionCode = "orders:read",
                            RoleId = new Guid("43f0ccca-e92a-4fa9-8d76-95e0746d33f6")
                        },
                        new
                        {
                            PermissionCode = "orders:create",
                            RoleId = new Guid("43f0ccca-e92a-4fa9-8d76-95e0746d33f6")
                        },
                        new
                        {
                            PermissionCode = "tickets:read",
                            RoleId = new Guid("43f0ccca-e92a-4fa9-8d76-95e0746d33f6")
                        },
                        new
                        {
                            PermissionCode = "tickets:check-in",
                            RoleId = new Guid("43f0ccca-e92a-4fa9-8d76-95e0746d33f6")
                        },
                        new
                        {
                            PermissionCode = "users:read",
                            RoleId = new Guid("7e7e4db6-0880-4b6a-b5d3-2d50e183f960")
                        },
                        new
                        {
                            PermissionCode = "users:update",
                            RoleId = new Guid("7e7e4db6-0880-4b6a-b5d3-2d50e183f960")
                        },
                        new
                        {
                            PermissionCode = "events:read",
                            RoleId = new Guid("7e7e4db6-0880-4b6a-b5d3-2d50e183f960")
                        },
                        new
                        {
                            PermissionCode = "events:search",
                            RoleId = new Guid("7e7e4db6-0880-4b6a-b5d3-2d50e183f960")
                        },
                        new
                        {
                            PermissionCode = "events:update",
                            RoleId = new Guid("7e7e4db6-0880-4b6a-b5d3-2d50e183f960")
                        },
                        new
                        {
                            PermissionCode = "ticket-types:read",
                            RoleId = new Guid("7e7e4db6-0880-4b6a-b5d3-2d50e183f960")
                        },
                        new
                        {
                            PermissionCode = "ticket-types:update",
                            RoleId = new Guid("7e7e4db6-0880-4b6a-b5d3-2d50e183f960")
                        },
                        new
                        {
                            PermissionCode = "categories:read",
                            RoleId = new Guid("7e7e4db6-0880-4b6a-b5d3-2d50e183f960")
                        },
                        new
                        {
                            PermissionCode = "categories:update",
                            RoleId = new Guid("7e7e4db6-0880-4b6a-b5d3-2d50e183f960")
                        },
                        new
                        {
                            PermissionCode = "carts:read",
                            RoleId = new Guid("7e7e4db6-0880-4b6a-b5d3-2d50e183f960")
                        },
                        new
                        {
                            PermissionCode = "carts:add",
                            RoleId = new Guid("7e7e4db6-0880-4b6a-b5d3-2d50e183f960")
                        },
                        new
                        {
                            PermissionCode = "carts:remove",
                            RoleId = new Guid("7e7e4db6-0880-4b6a-b5d3-2d50e183f960")
                        },
                        new
                        {
                            PermissionCode = "orders:read",
                            RoleId = new Guid("7e7e4db6-0880-4b6a-b5d3-2d50e183f960")
                        },
                        new
                        {
                            PermissionCode = "orders:create",
                            RoleId = new Guid("7e7e4db6-0880-4b6a-b5d3-2d50e183f960")
                        },
                        new
                        {
                            PermissionCode = "tickets:read",
                            RoleId = new Guid("7e7e4db6-0880-4b6a-b5d3-2d50e183f960")
                        },
                        new
                        {
                            PermissionCode = "tickets:check-in",
                            RoleId = new Guid("7e7e4db6-0880-4b6a-b5d3-2d50e183f960")
                        },
                        new
                        {
                            PermissionCode = "event-statistics:read",
                            RoleId = new Guid("7e7e4db6-0880-4b6a-b5d3-2d50e183f960")
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolesId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("user_roles", "users");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("Evently.Modules.Users.Domain.Users.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Evently.Modules.Users.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Evently.Modules.Users.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Evently.Modules.Users.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
